/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-21 01:42:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class orderConfirm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		// 체크 -> 배송 정보에 고객 정보 복사\r\n");
      out.write("		$(\"#same_address\").on(\"click\", function(){\r\n");
      out.write("			var check = this.checked; // check 상태 저장\r\n");
      out.write("			if(check == true) {\r\n");
      out.write("				var mname = $(\"#mname\").val()\r\n");
      out.write("				var mpost = $(\"#mpost\").val()\r\n");
      out.write("				var maddress1 = $(\"#maddress1\").val()\r\n");
      out.write("				var maddress2 = $(\"#maddress2\").val()\r\n");
      out.write("				var mphone = $(\"#mphone\").val()\r\n");
      out.write("				// 고객정보 값을 배송지 정보에 설정\r\n");
      out.write("				$(\"#orderName\").val(mname);\r\n");
      out.write("				$(\"#sample4_postcode\").val(mpost);\r\n");
      out.write("				$(\"#sample4_roadAddress\").val(maddress1);\r\n");
      out.write("				$(\"#sample4_jibunAddress\").val(maddress2);\r\n");
      out.write("				$(\"#sample4_jibunAddress\").val(maddress2);\r\n");
      out.write("				$(\"#phone\").val(mphone);\r\n");
      out.write("			} else {\r\n");
      out.write("				// 배송지 정보값을 \"\"로 설정\r\n");
      out.write("				$(\"#orderName\").val(\"\");\r\n");
      out.write("				$(\"#sample4_postcode\").val(\"\");\r\n");
      out.write("				$(\"#sample4_roadAddress\").val(\"\");\r\n");
      out.write("				$(\"#sample4_jibunAddress\").val(\"\");\r\n");
      out.write("				$(\"#phone\").val(\"\");\r\n");
      out.write("			}	\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// 결제 버튼 이벤트 처리\r\n");
      out.write("		$(\"#orderDoneBtn\").on(\"click\", function(){\r\n");
      out.write("			\r\n");
      out.write("			var f = $(\"form\")[0];\r\n");
      out.write("			f.action=\"OrderDoneServlet\";\r\n");
      out.write("			f.method=\"get\";\r\n");
      out.write("			f.submit(); // input button이기 때문에 명시적으로 submit 해줘야한다.\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<form name=\"myForm\" method=\"get\" action=\"\">\r\n");
      out.write("\r\n");
      out.write("	<!-- 결제하기위해 상품 정보들 submit과 함께 넘겨주기 -->\r\n");
      out.write("    <input type=\"hidden\"  name=\"gCode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cDTO.gCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" >\r\n");
      out.write("    <input type=\"hidden\"  name=\"gName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cDTO.gName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" >\r\n");
      out.write("    <input type=\"hidden\"  name=\"gPrice\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cDTO.gPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" >\r\n");
      out.write("    <input type=\"hidden\"  name=\"gSize\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cDTO.gSize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" >\r\n");
      out.write("    <input type=\"hidden\"  name=\"gColor\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cDTO.gColor}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" >\r\n");
      out.write("    <input type=\"hidden\"  name=\"gAmount\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cDTO.gAmount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" >\r\n");
      out.write("    <input type=\"hidden\"  name=\"gImage\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cDTO.gImage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" >\r\n");
      out.write("    \r\n");
      out.write("    <!-- Cart 테이블에서 삭제할 num도 같이 전달 -->\r\n");
      out.write("    <input type=\"hidden\"  name=\"num\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cDTO.num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" >\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<table width=\"80%\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td height=\"30\">\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td><b>주문상품 확인</b></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td height=\"15\">\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>\r\n");
      out.write("				<hr size=\"1\" color=\"CCCCCC\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td height=\"5\">\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>\r\n");
      out.write("				<table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td class=\"td_default\" align=\"center\"><strong>주문번호</strong></td>\r\n");
      out.write("						<td class=\"td_default\" align=\"center\" colspan=\"2\"><strong>상품정보</strong></td>\r\n");
      out.write("						<td class=\"td_default\" align=\"center\"><strong>판매가</strong></td>\r\n");
      out.write("						<td class=\"td_default\" align=\"center\" colspan=\"2\"><strong>수량</strong></td>\r\n");
      out.write("\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"4\">\r\n");
      out.write("							<hr size=\"1\" >\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td class=\"td_default\" width=\"80\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cDTO.num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("						<td class=\"td_default\" width=\"80\"><img\r\n");
      out.write("							src=\"images/items/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cDTO.gImage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".gif\" border=\"0\" align=\"center\"\r\n");
      out.write("							width=\"80\" /></td>\r\n");
      out.write("						<td class=\"td_default\" width=\"300\" style='padding-left: 30px'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cDTO.gName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("							<br> <font size=\"2\" color=\"#665b5f\">[옵션 : 사이즈(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cDTO.gSize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\r\n");
      out.write("								, 색상(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cDTO.gColor}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")]\r\n");
      out.write("						</font></td>\r\n");
      out.write("						<td class=\"td_default\" align=\"center\" width=\"110\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cDTO.gPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("						</td>\r\n");
      out.write("						<td class=\"td_default\" align=\"center\" width=\"90\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cDTO.gAmount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td height=\"30\"></td>\r\n");
      out.write("						<td class=\"td_default\" align=\"right\">총 결제 금액 :</td>\r\n");
      out.write("						<td class=\"td_default\" align='right'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cDTO.gAmount * cDTO.gPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("원</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table> <tr>\r\n");
      out.write("			<td>\r\n");
      out.write("					<hr size=\"1\" color=\"CCCCCC\">\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("	<!--  고객 정보 시작-->\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td height=\"30\">\r\n");
      out.write("	\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><b>고객 정보</b></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"15\">\r\n");
      out.write("	\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>\r\n");
      out.write("			<table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"1\"\r\n");
      out.write("					style=\"border-collapse:collapse\" bordercolor=\"#CCCCCC\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td width=\"125\" height=\"35\" class=\"td_default\">\r\n");
      out.write("						\r\n");
      out.write("						이 름\r\n");
      out.write("					</td>\r\n");
      out.write("					<td height=\"35\" class=\"td_default\">\r\n");
      out.write("						<input class=\"input_default\" type=\"text\" id=\"mname\" size=\"20\"\r\n");
      out.write("							maxlength=\"20\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mDTO.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></input>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td height=\"35\" class=\"td_default\">\r\n");
      out.write("						\r\n");
      out.write("						우편번호\r\n");
      out.write("					</td>\r\n");
      out.write("					<td height=\"35\" class=\"td_default\">\r\n");
      out.write("						<input class=\"input_default\" type=\"text\" id=\"mpost\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mDTO.post}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></input>\r\n");
      out.write("						\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td height=\"35\" class=\"td_default\">\r\n");
      out.write("						\r\n");
      out.write("						주 소\r\n");
      out.write("					</td>\r\n");
      out.write("					<td height=\"35\" class=\"td_default\">\r\n");
      out.write("						<input class=\"input_default\" type=\"text\" id=\"maddress1\" size=\"35\"\r\n");
      out.write("							maxlength=\"200\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mDTO.addr1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></input><br>\r\n");
      out.write("						<input class=\"input_default\" type=\"text\" id=\"maddress2\" size=\"35\"\r\n");
      out.write("							maxlength=\"200\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mDTO.addr2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></input>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td height=\"35\" class=\"td_default\">\r\n");
      out.write("						휴대전화\r\n");
      out.write("					</td>\r\n");
      out.write("					<td height=\"35\" class=\"td_default\">\r\n");
      out.write("						<input class=\"input_default\" type=\"text\" id=\"mphone\" size=\"15\"\r\n");
      out.write("							maxlength=\"15\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mDTO.phone1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mDTO.phone2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mDTO.phone3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></input>\r\n");
      out.write("						\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>							\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("<!--  고객 정보 끝-->\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"30\">\r\n");
      out.write("	\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr> \r\n");
      out.write("		<td class=\"td_default\">\r\n");
      out.write("		  <input type=\"checkbox\" name=\"same_address\" id=\"same_address\"> 배송지가 동일할 경우 선택하세요.\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("<!--  배송지 정보 시작-->\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"30\">\r\n");
      out.write("	\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><b>배송지 정보</b></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"15\">\r\n");
      out.write("	\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>\r\n");
      out.write("			<table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"1\"\r\n");
      out.write("					style=\"border-collapse:collapse\" bordercolor=\"#CCCCCC\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td width=\"125\" height=\"35\" class=\"td_default\">\r\n");
      out.write("						\r\n");
      out.write("						이 름\r\n");
      out.write("					</td>\r\n");
      out.write("					<td height=\"35\" class=\"td_default\">\r\n");
      out.write("						<input class=\"input_default\" type=\"text\" id=\"orderName\"\r\n");
      out.write("							name=\"orderName\" size=\"20\" maxlength=\"20\" value=\"\"></input>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td height=\"35\" class=\"td_default\">\r\n");
      out.write("						\r\n");
      out.write("						우편번호\r\n");
      out.write("					</td>\r\n");
      out.write("					<td height=\"35\" class=\"td_default\">\r\n");
      out.write("<!-- 다음주소 시작--> <!-- 쿼리스트링으로 넘겨주기 위해 name 추가 -->\r\n");
      out.write("<input type=\"text\" name=\"post\" id=\"sample4_postcode\" placeholder=\"우편번호\">\r\n");
      out.write("<input type=\"button\" onclick=\"sample4_execDaumPostcode()\" value=\"우편번호 찾기\"><br>\r\n");
      out.write("<input type=\"text\" name=\"addr1\" id=\"sample4_roadAddress\" placeholder=\"도로명주소\">\r\n");
      out.write("<input type=\"text\" name=\"addr2\" id=\"sample4_jibunAddress\" placeholder=\"지번주소\">\r\n");
      out.write("<span id=\"guide\" style=\"color:#999\"></span>\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    //본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.\r\n");
      out.write("    function sample4_execDaumPostcode() {\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 도로명 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var fullRoadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("                var extraRoadAddr = ''; // 도로명 조합형 주소 변수\r\n");
      out.write("\r\n");
      out.write("                // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                    extraRoadAddr += data.bname;\r\n");
      out.write("                }\r\n");
      out.write("                // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                   extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                }\r\n");
      out.write("                // 도로명, 지번 조합형 주소가 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                if(extraRoadAddr !== ''){\r\n");
      out.write("                    extraRoadAddr = ' (' + extraRoadAddr + ')';\r\n");
      out.write("                }\r\n");
      out.write("                // 도로명, 지번 주소의 유무에 따라 해당 조합형 주소를 추가한다.\r\n");
      out.write("                if(fullRoadAddr !== ''){\r\n");
      out.write("                    fullRoadAddr += extraRoadAddr;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                document.getElementById('sample4_postcode').value = data.zonecode; //5자리 새우편번호 사용\r\n");
      out.write("                document.getElementById('sample4_roadAddress').value = fullRoadAddr;\r\n");
      out.write("                document.getElementById('sample4_jibunAddress').value = data.jibunAddress;\r\n");
      out.write("\r\n");
      out.write("                // 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.\r\n");
      out.write("                if(data.autoRoadAddress) {\r\n");
      out.write("                    //예상되는 도로명 주소에 조합형 주소를 추가한다.\r\n");
      out.write("                    var expRoadAddr = data.autoRoadAddress + extraRoadAddr;\r\n");
      out.write("                    document.getElementById('guide').innerHTML = '(예상 도로명 주소 : ' + expRoadAddr + ')';\r\n");
      out.write("\r\n");
      out.write("                } else if(data.autoJibunAddress) {\r\n");
      out.write("                    var expJibunAddr = data.autoJibunAddress;\r\n");
      out.write("                    document.getElementById('guide').innerHTML = '(예상 지번 주소 : ' + expJibunAddr + ')';\r\n");
      out.write("\r\n");
      out.write("                } else {\r\n");
      out.write("                    document.getElementById('guide').innerHTML = '';\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }).open();\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 다음주소 끝 -->\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td height=\"35\" class=\"td_default\">\r\n");
      out.write("						\r\n");
      out.write("						휴대전화\r\n");
      out.write("					</td>\r\n");
      out.write("					<td height=\"35\" class=\"td_default\">\r\n");
      out.write("						<input class=\"input_default\" type=\"text\" id=\"phone\"\r\n");
      out.write("							name=\"phone\" size=\"15\" maxlength=\"15\" value=\"\"></input>\r\n");
      out.write("					\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>							\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("<!--  배송지 정보 끝-->\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"30\">\r\n");
      out.write("	\r\n");
      out.write("		</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><b>결제수단</b></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"15\">\r\n");
      out.write("	\r\n");
      out.write("		</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>\r\n");
      out.write("			<table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"1\"\r\n");
      out.write("					style=\"border-collapse:collapse\" bordercolor=\"#CCCCCC\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td width=\"125\" height=\"35\" class=\"td_default\">\r\n");
      out.write("						<input type=\"radio\" name=\"payMethod\" value=\"신용카드\" checked>신용카드</input>\r\n");
      out.write("						\r\n");
      out.write("						<input type=\"radio\" name=\"payMethod\" value=\"계좌이체\">계좌이체</input>\r\n");
      out.write("						\r\n");
      out.write("						<input type=\"radio\" name=\"payMethod\" value=\"무통장 입금\">무통장 입금</input>\r\n");
      out.write("					</td>\r\n");
      out.write("					\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("			</table>							\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"30\">\r\n");
      out.write("	\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td class=\"td_default\" align=\"center\">\r\n");
      out.write("			<input type='button' value='취소' onclick=\"javascript:history.back()\">	\r\n");
      out.write("			<input type='button' value='결제하기'\" id=\"orderDoneBtn\"> <!-- OderDoneServlet에 주문 정보 보냄 -->\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</FORM>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
