/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-20 07:20:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.goods;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class goodsRetrieve_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- jquery -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		// 주문수량 up\r\n");
      out.write("		$(\"#up\").on(\"click\", function(){\r\n");
      out.write("			var gAmount = Number.parseInt($(\"#gAmount\").val());\r\n");
      out.write("			$(\"#gAmount\").val(++gAmount);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// 주문수량 down ==> 최저값 1\r\n");
      out.write("		$(\"#down\").on(\"click\", function(){\r\n");
      out.write("			var gAmount = Number.parseInt($(\"#gAmount\").val());\r\n");
      out.write("			if(gAmount==1) {\r\n");
      out.write("				$(\"#gAmount\").val(1);\r\n");
      out.write("			}else {\r\n");
      out.write("				$(\"#gAmount\").val(--gAmount);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// 장바구니 버튼 이벤트 처리\r\n");
      out.write("		$(cartBtn).on(\"click\", function(){\r\n");
      out.write("			var f = $(\"#myForm\")[0]; // form객체를 변수로 받음 => 배열로 받음\r\n");
      out.write("			f.action=\"CartAddServlet\" // 장바구니 버튼 클릭시 form태그의 액션값이 변경됨 => 첫번째 form태그임을 알려주기 위해 인덱스 적용\r\n");
      out.write("			\r\n");
      out.write("			// 다른 속성을 바꿀 때도 action과 마찬가지로 f.속성명=값 형식으로 설정해주면 된다.\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// 구매 버튼 이벤트 처리\r\n");
      out.write("		$(buyBtn).on(\"click\", function(){\r\n");
      out.write("			var f = $(\"#myForm\")[0]; // form객체를 변수로 받음 => 배열로 받음\r\n");
      out.write("			f.action=\"main\" // 장바구니 버튼 클릭시 form태그의 액션값이 변경됨 => 첫번째 form태그임을 알려주기 위해 인덱스 적용\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 구매/장바구니 버튼에 따라 action값이 다르도록(동적으로) 설정해줘야 한다. -->\r\n");
      out.write("<form name=\"goodRetrieveForm\" id=\"myForm\" method=\"GET\" action=\"#\">\r\n");
      out.write("		<!-- 선택 옵션 외의 넘겨줘야 할 정보들은 hidden으로 명시 -->\r\n");
      out.write("	    <input type=\"hidden\" name=\"gImage\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ goodsRetrieve.gImage }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> \r\n");
      out.write("	    <input type=\"hidden\" name=\"gCode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ goodsRetrieve.gCode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("	    <input type=\"hidden\" name=\"gName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ goodsRetrieve.gName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("	    <input type=\"hidden\" name=\"gPrice\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ goodsRetrieve.gPrice }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("	<table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td height=\"30\">\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>\r\n");
      out.write("				<table align=\"center\" width=\"710\" cellspacing=\"0\" cellpadding=\"0\"\r\n");
      out.write("					border=\"0\" style='margin-left: 30px'>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td class=\"td_default\"><font size=\"5\"><b>- 상품 정보 -</b></font>\r\n");
      out.write("							&nbsp;</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td height=\"5\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td height=\"1\" colspan=\"8\" bgcolor=\"CECECE\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td height=\"10\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td rowspan=\"7\"><img src=\"images/items/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ goodsRetrieve.gImage }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".gif\"\r\n");
      out.write("							border=\"0\" align=\"center\" width=\"300\" /></td>\r\n");
      out.write("						<td class=\"td_title\">제품코드</td>\r\n");
      out.write("						<td class=\"td_default\" colspan=\"2\" style='padding-left: 30px'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ goodsRetrieve.gCode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td class=\"td_title\">상품명</td>\r\n");
      out.write("						<td class=\"td_default\" colspan=\"2\" style='padding-left: 30px'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ goodsRetrieve.gName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td class=\"td_title\">가격</td>\r\n");
      out.write("\r\n");
      out.write("						<td class=\"td_red\" colspan=\"2\" style='padding-left: 30px'>\r\n");
      out.write("						￦");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ goodsRetrieve.gPrice }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td class=\"td_title\">배송비</td>\r\n");
      out.write("						<td colspan=\"2\"><font color=\"#2e56a9\" size=\"2\"\r\n");
      out.write("							style='padding-left: 30px'><b> 무료배송</b> </font> <font size=\"2\">(도서\r\n");
      out.write("								산간지역 별도 배송비 추가)</font></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td class=\"td_title\" rowspan=\"2\">상품옵션</td>\r\n");
      out.write("						<td colspan=\"2\" style='padding-left: 30px'><select\r\n");
      out.write("							class=\"select_change\" size=\"1\" name=\"gSize\" id=\"gSize\">\r\n");
      out.write("								<option selected value=\"사이즈선택\">사이즈선택</option>\r\n");
      out.write("								<option value=\"L\">L</option>\r\n");
      out.write("								<option value=\"M\">M</option>\r\n");
      out.write("								<option value=\"S\">S</option>\r\n");
      out.write("						</select></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"2\" style='padding-left: 30px'><select\r\n");
      out.write("							class=\"select_change\" size=\"1\" name=\"gColor\"\r\n");
      out.write("							id=\"gColor\">\r\n");
      out.write("								<option selected value=\"색상선택\">색상선택</option>\r\n");
      out.write("								<option value=\"navy\">navy</option>\r\n");
      out.write("								<option value=\"black\">black</option>\r\n");
      out.write("								<option value=\"ivory\">ivory</option>\r\n");
      out.write("								<option value=\"white\">white</option>\r\n");
      out.write("								<option value=\"gray\">gray</option>\r\n");
      out.write("						</select></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td class=\"td_title\">주문수량</td>\r\n");
      out.write("						<td style=\"padding-left: 30px\">\r\n");
      out.write("						<input type=\"text\"\r\n");
      out.write("							   name=\"gAmount\" value=\"1\" id=\"gAmount\"\r\n");
      out.write("							   style=\"text-align: right; height: 18px\"> \r\n");
      out.write("						<img src=\"images/up.PNG\" id=\"up\"> <img src=\"images/down.PNG\"\r\n");
      out.write("							 id=\"down\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("\r\n");
      out.write("	<br> <button id=\"buyBtn\">구매</button>\r\n");
      out.write("	&nbsp;&nbsp;\r\n");
      out.write("	<button id=\"cartBtn\">장바구니</button>\r\n");
      out.write("</form>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
